// Auto-generated by scripts/minify-webview-js.js
// DO NOT EDIT - Run 'yarn minify-webview' to regenerate

export const minifiedConsoleIntercept = "[\"log\",\"warn\",\"error\",\"info\"].forEach(function(n){var e=console[n];console[n]=function(){e.apply(console,arguments);try{var t=Array.from(arguments).map(function(r){if(typeof r==\"object\")try{return JSON.stringify(r)}catch(o){return\"[Object]\"}return String(r)});window.ReactNativeWebView.postMessage(JSON.stringify({type:\"console\",method:n,args:t}))}catch(r){}}});\n";
